package main.scala

import scala.actors.threadpool.Executors

/**
  * Created by jules on 12/30/15.
  * In this example, I use an Executor Service with a pool threads to generate devices information concurrently. Not only it's an illustration
  * of Scala expressive, succinct, and declarative way of programming, it shows the power of its functional programming.
  *
  * Note how foreach methods are used in List collection to submit jobs, to iterate over each List of Maps, and to print each
  * device Map. You can't help but admire the tightness of its API.
  *
  * Simple few lies of Scala.
  */
object DeviceIoTExecutor {

  /**
    * Using the foreach method of the List or Collection, print each device Map
    * @param elem
    */
  def processMap(elem: List[scala.collection.mutable.Map[String, String]]): Unit = {
    println("Processing each device map...")
    elem.foreach(println(_))
  }

  def main(args:Array[String]): Unit = {

    val ndevices = args(0).toInt
    if (ndevices % 3 != 0) {
      println("Number of devices must be multiple of 3.")
      System.exit(1)
    }
    val cores = 3
    val pool = Executors.newFixedThreadPool(cores)
    val multiple = ndevices / 3
    var devGenerators: List[DeviceIoTGenerators] = List()
    //create list of three Device Generators Runnables
    devGenerators = devGenerators.::(new DeviceIoTGenerators(1 until multiple))
    devGenerators = devGenerators.::(new DeviceIoTGenerators(multiple + 1 until 2 * multiple))
    devGenerators = devGenerators.::(new DeviceIoTGenerators((2 * multiple) + 1 until 3 * multiple))
    // Using foreach method on the list, submit 3 runnables to the executor service thread
    devGenerators.foreach(pool.submit(_))
    // let them finish; we could use LatchCountDown if we wanted, but since this is a simple case, a minor Sleep shall suffice
    Thread.sleep(2000)
    // reverse the order the List, since in Scala, for efficient, lists are appended to the front.
    devGenerators = devGenerators.reverse
    // Using foreach method, iteratate for each List[Map[String, String]] generated by the Runnables
    devGenerators.foreach(e => processMap {
      e.getDeviceBatches()
    })
    println("Finished...")
  }

}
